
clusterName: voyager-cluster
karpenterVersion: v0.33.0
karpenterApiVersion: karpenter.sh/v1
settings:
  aws:
    defaultInstanceProfile: karpenter-node-instance-profile
    clusterEndpoint: https://1EBBAD31A904C4C42E819438A2477EF3.gr7.ap-northeast-2.eks.amazonaws.com
    roleArn: arn:aws:iam::009537862357:role/karpenter-controller-role

replicas: 1
image:
  repository: public.ecr.aws/karpenter/controller
  tag: "${.Values.karpenterVersion}"
serviceAccount:
  create: true
  name: karpenter
  annotations:
    eks.amazonaws.com/role-arn: "${.Values.settings.aws.roleArn}"
controller:
  args:
    - --cluster-name=voyager-cluster