apiVersion: v1
kind: Service
metadata:
  name: {{ include "hello-chart.fullname" . | trunc 63 }}
  labels:
    app.kubernetes.io/name: {{ include "hello-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ default "ClusterIP" .Values.service.type }}
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ default 80 .Values.service.port }}
      targetPort: {{ default 8080 .Values.service.targetPort }}
      protocol: TCP
      name: http